spring:
  application:
    name: calculator-microservice
  output:
    ansi:
      enabled: always
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36}.%M() : %m%n)"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
